## Transactions

In [1]:
import pandas as pd

df_8 = pd.read_csv("../Datasets/transactions.csv")
df_8.head()

      CUST_ID       DATE       EXP_TYPE  AMOUNT
0  CI6XLYUMQK  9/11/2015   Motor/Travel   20.27
1  CI6XLYUMQK   2/8/2017   Motor/Travel   12.85
2  CI6XLYUMQK   8/1/2015        Housing  383.80
3  CI6XLYUMQK  3/16/2019  Entertainment    5.72
4  CI6XLYUMQK  5/15/2015  Entertainment   11.06

In [2]:
df_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 4 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   CUST_ID   1048575 non-null  object
 1   DATE      1048575 non-null  object
 2   EXP_TYPE  1048575 non-null  object
 3   AMOUNT    1048575 non-null  float64
dtypes: float64(1), object(3)
memory usage: 32.0+ MB

In [3]:
# Count number of transactions per customer
customer_counts = df_8["CUST_ID"].value_counts()

# Filter customers with more than 1000 transactions
customers_over_1000 = customer_counts[customer_counts > 1000]

print("Customers with over 1000 transactions:")
print(customers_over_1000)

Customers with over 1000 transactions:
CUST_ID
C6CB8Q0RJY    9885
CO8O4SVZGO    9023
C25X0A4MR6    8919
CS43O74SET    8827
C3UPK5Q1EF    8711
              ...
CT0IBPV84W    1102
CEPO9ZYUSM    1066
C4GT8R8ZOI    1049
CMIDA9AWX8    1041
C2A82UAGI8    1005
Name: count, Length: 254, dtype: int64

In [4]:
# total transaction for all customers 
customers_over_1000.sum()

np.int64(1040203)

In [5]:
# Create the new dataset containing ONLY those customers
df_8 = df_8[df_8["CUST_ID"].isin(customers_over_1000.index)]

In [6]:
df_8.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1040203 entries, 0 to 1048285
Data columns (total 4 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   CUST_ID   1040203 non-null  object
 1   DATE      1040203 non-null  object
 2   EXP_TYPE  1040203 non-null  object
 3   AMOUNT    1040203 non-null  float64
dtypes: float64(1), object(3)
memory usage: 39.7+ MB

In [7]:
df_8.head()

      CUST_ID       DATE       EXP_TYPE  AMOUNT
0  CI6XLYUMQK  9/11/2015   Motor/Travel   20.27
1  CI6XLYUMQK   2/8/2017   Motor/Travel   12.85
2  CI6XLYUMQK   8/1/2015        Housing  383.80
3  CI6XLYUMQK  3/16/2019  Entertainment    5.72
4  CI6XLYUMQK  5/15/2015  Entertainment   11.06

In [8]:
# Create TransactionID for each transaction
df_8 = df_8.reset_index(drop=True)

df_8["TransactionID"] = df_8.index + 1
df_8["TransactionID"] = df_8["TransactionID"].apply(lambda x: f"TRX8_{str(x).zfill(6)}")

In [9]:
df_8.head()

      CUST_ID       DATE       EXP_TYPE  AMOUNT TransactionID
0  CI6XLYUMQK  9/11/2015   Motor/Travel   20.27   TRX8_000001
1  CI6XLYUMQK   2/8/2017   Motor/Travel   12.85   TRX8_000002
2  CI6XLYUMQK   8/1/2015        Housing  383.80   TRX8_000003
3  CI6XLYUMQK  3/16/2019  Entertainment    5.72   TRX8_000004
4  CI6XLYUMQK  5/15/2015  Entertainment   11.06   TRX8_000005

In [10]:
# Create a mapping from CUST_ID → US8001, US8002, ...
df_8 = df_8.reset_index(drop=True)

# Get unique customers
unique_customers = df_8["CUST_ID"].unique()

# Create mapping: each customer → US8001, US8002, ...
user_map = {cust: f"US8{str(i+1).zfill(3)}" for i, cust in enumerate(unique_customers)}

user_map

{'CI6XLYUMQK': 'US8001',
 'CF7T5CWU3D': 'US8002',
 'CCWG6X0ANH': 'US8003',
 'CNCHG01OO4': 'US8004',
 'CH78LNZBLA': 'US8005',
 'CY2LOCIAEY': 'US8006',
 'CRHR4XOQDC': 'US8007',
 'C45DLPP4XB': 'US8008',
 'C8V75CO923': 'US8009',
 'C44B7OZRJJ': 'US8010',
 'C90ORLQ6BB': 'US8011',
 'CMCVL0MTE7': 'US8012',
 'CQUF4RFT6A': 'US8013',
 'C1UWXDUYCU': 'US8014',
 'C72IQGSR4Q': 'US8015',
 'CW8H27KDRU': 'US8016',
 'C6XJ17N2BM': 'US8017',
 'CNZP5AM1TR': 'US8018',
 'C66T7GD6L3': 'US8019',
 'CFEUQPQLQ6': 'US8020',
 'C9978KJPIF': 'US8021',
 'CW3W59PX42': 'US8022',
 'C4IYL0WW99': 'US8023',
 'C3YEX3PF91': 'US8024',
 'CQ4Z9CMION': 'US8025',
 'CC1FUR4CWU': 'US8026',
 'CDZVNYMA74': 'US8027',
 'CVPBSTACKK': 'US8028',
 'CI5V07EPCQ': 'US8029',
 'C90PUOTE5I': 'US8030',
 'COA0991DIV': 'US8031',
 'COGX2XX87L': 'US8032',
 'CXJRWQL4L2': 'US8033',
 'C9N9LXDIBQ': 'US8034',
 'CVWCYSIRLE': 'US8035',
 'CP32TXZAEC': 'US8036',
 'C9ELFE55KM': 'US8037',
 'C1FNGDWX5C': 'US8038',
 'C3UPK5Q1EF': 'US8039',
 'CJF1VMHF7M': 'US8040',
 'C2QESXROV3': 'US8041',
 'CZR5G7K53H': 'US8042',
 'CTL3O74MDD': 'US8043',
 'C4XHKCV9KQ': 'US8044',
 'CD48770UB4': 'US8045',
 'CTUS3INTVX': 'US8046',
 'CEGD867N1X': 'US8047',
 'CE7FXMQ88J': 'US8048',
 'C3XTO0S0I8': 'US8049',
 'C33CAPHI3E': 'US8050',
 'CAQ642YPDK': 'US8051',
 'CPURU3SSF2': 'US8052',
 'C2WI4SC6MG': 'US8053',
 'CN5ZZXI6VM': 'US8054',
 'CU4LW4VPC1': 'US8055',
 'CGMLNAUYQO': 'US8056',
 'C8UDWZ8K37': 'US8057',
 'COHZ0O9GJG': 'US8058',
 'CQIPAAJBUP': 'US8059',
 'CSKI1S4NKZ': 'US8060',
 'CTT8I1PS2E': 'US8061',
 'C9VAOO14IK': 'US8062',
 'CBOL0WSULQ': 'US8063',
 'C82OYS39TI': 'US8064',
 'CC6SINMTHK': 'US8065',
 'C3R2E1W9B1': 'US8066',
 'CBCXE3YGD5': 'US8067',
 'C59KR68HMQ': 'US8068',
 'CNINP5HVT7': 'US8069',
 'C60Z3X99RC': 'US8070',
 'CR8UG9QNX5': 'US8071',
 'C6IQZ0J7U8': 'US8072',
 'C79M53BK5P': 'US8073',
 'CEL53DXZOM': 'US8074',
 'CHCOJ4L4JQ': 'US8075',
 'CI2YDWQK31': 'US8076',
 'CDLEFXY8S5': 'US8077',
 'CH40R8TDFT': 'US8078',
 'C8L2CFMJHA': 'US8079',
 'C9448LCBPB': 'US8080',
 'CBBU6Y04JF': 'US8081',
 'CV3SSMJWI7': 'US8082',
 'CCITXYDYZL': 'US8083',
 'C2APRNH3W8': 'US8084',
 'CKU7BWV5J1': 'US8085',
 'C1T4U6EUEE': 'US8086',
 'C208N9HJKY': 'US8087',
 'CS43O74SET': 'US8088',
 'C1PCHD2TVM': 'US8089',
 'CBK83K6TNL': 'US8090',
 'C72O1UKD7J': 'US8091',
 'CX3Q6656VP': 'US8092',
 'CWGA89TKA4': 'US8093',
 'CXPYUZ3TB3': 'US8094',
 'CBYTIV8QZO': 'US8095',
 'C2A82UAGI8': 'US8096',
 'CXQRZOU4O3': 'US8097',
 'CNBVZYS34M': 'US8098',
 'CBP26STSHJ': 'US8099',
 'CEPO9ZYUSM': 'US8100',
 'CI8AR26XSM': 'US8101',
 'CQL065SOC6': 'US8102',
 'CTSMXRZR4O': 'US8103',
 'CD22W0INWK': 'US8104',
 'CR2NYG9RHM': 'US8105',
 'C0G0WH0L1L': 'US8106',
 'C6CB8Q0RJY': 'US8107',
 'C9NIQ12KO4': 'US8108',
 'CQACK7IHXH': 'US8109',
 'C4IUYNJZX5': 'US8110',
 'CS8LQ9OI76': 'US8111',
 'CSL96W997N': 'US8112',
 'CFRSNNVXS3': 'US8113',
 'CLFFIV07CI': 'US8114',
 'CD13KGCC7L': 'US8115',
 'CJK8LV5FBR': 'US8116',
 'CSJFLBEHE8': 'US8117',
 'CDV0EIYHN2': 'US8118',
 'CQWRXVIPCI': 'US8119',
 'CJKWX8ND1G': 'US8120',
 'CA1OGDCSV2': 'US8121',
 'CP3U46N4SO': 'US8122',
 'C47PA0HCNN': 'US8123',
 'C859RLGGKP': 'US8124',
 'CTSC7GFGMV': 'US8125',
 'CG1HDVO9L4': 'US8126',
 'CEF4GWESH0': 'US8127',
 'C7I3ORUG5O': 'US8128',
 'C12F21MNJ5': 'US8129',
 'C1HQ39HF3W': 'US8130',
 'C49S90S80U': 'US8131',
 'C43VUVGPI5': 'US8132',
 'C36I47AYA8': 'US8133',
 'C1WLU2TB3Z': 'US8134',
 'CMIDA9AWX8': 'US8135',
 'CD51UTOCQH': 'US8136',
 'CHRRP675CR': 'US8137',
 'CT6ZN4D1X5': 'US8138',
 'CULLAJ9D7Z': 'US8139',
 'CKA2W4P04M': 'US8140',
 'CG7UJOQ2UY': 'US8141',
 'CZVRV9IMJ3': 'US8142',
 'CPZ9XNHD5J': 'US8143',
 'CXISJPFOCA': 'US8144',
 'CU0ICI0HQK': 'US8145',
 'CLCJTMIQ5Y': 'US8146',
 'CIYTCNQNCQ': 'US8147',
 'C1LWQOVAAO': 'US8148',
 'C4GT8R8ZOI': 'US8149',
 'CPL2WYXNPN': 'US8150',
 'CKVD7J5MAX': 'US8151',
 'C4GP1UE2S2': 'US8152',
 'CKSHV2N1KX': 'US8153',
 'CPYQROVZ2I': 'US8154',
 'C6TUXH0AXB': 'US8155',
 'C7B47KO957': 'US8156',
 'CKB8C79AIZ': 'US8157',
 'CC15DQWYY0': 'US8158',
 'C7QFMK77CG': 'US8159',
 'C1KJ9PR9C2': 'US8160',
 'CAIJX5735O': 'US8161',
 'C58DL3ECRV': 'US8162',
 'CP9YR8E39K': 'US8163',
 'CEAMR3G4G4': 'US8164',
 'CY3GXV6G7M': 'US8165',
 'CPLVQV8DH4': 'US8166',
 'CJG561J4M0': 'US8167',
 'C3V4XY8QI8': 'US8168',
 'CWL7PH6A0V': 'US8169',
 'CA3YDJUO8R': 'US8170',
 'CPOCPGS7C3': 'US8171',
 'CXZZH3Z7BB': 'US8172',
 'CBSJZK910W': 'US8173',
 'CONE3YS9Q1': 'US8174',
 'CPCISN05A4': 'US8175',
 'CEQVS6Y6KE': 'US8176',
 'CQJZ5TIPXN': 'US8177',
 'C8VQC3636U': 'US8178',
 'C0TDUBUWCF': 'US8179',
 'CZNN531LC0': 'US8180',
 'C7O4OKWKKD': 'US8181',
 'CTK6DEB0W1': 'US8182',
 'CK9QWARSO1': 'US8183',
 'CSPYRE19GV': 'US8184',
 'CIQAY63DGA': 'US8185',
 'CGYIMGPMUI': 'US8186',
 'CCXTDEVCOU': 'US8187',
 'CA5QWE8CHW': 'US8188',
 'C1QMSUVNP3': 'US8189',
 'C24QN6BC73': 'US8190',
 'C7E11XGAAF': 'US8191',
 'CF2SQQ0BT5': 'US8192',
 'C0AGWVZKHG': 'US8193',
 'C8MU63K6F9': 'US8194',
 'CIXMO16PWT': 'US8195',
 'CDDCQ7DSI7': 'US8196',
 'CS5KDQ2QL8': 'US8197',
 'CXWG9LCN4A': 'US8198',
 'CH6BHRUCD8': 'US8199',
 'CWWIG216EI': 'US8200',
 'CR14KB0TPO': 'US8201',
 'CJK66OM5U5': 'US8202',
 'CU847BOGSV': 'US8203',
 'C238HA5HEM': 'US8204',
 'CU1FJ0TD7H': 'US8205',
 'CTDE2OXLR9': 'US8206',
 'CC0MMDAFQV': 'US8207',
 'CJGCVPZJI2': 'US8208',
 'C0ED9T4KLL': 'US8209',
 'C8WGLG1BZZ': 'US8210',
 'C0MNORA8M0': 'US8211',
 'CIXKGCOEQR': 'US8212',
 'C6VIRXN8O5': 'US8213',
 'CV8QGRDUD0': 'US8214',
 'CSQGQLS7AC': 'US8215',
 'C5S625LDFX': 'US8216',
 'CGLM1R1TRM': 'US8217',
 'CGRLNE0ZV8': 'US8218',
 'CXE8AVNPMN': 'US8219',
 'C7KZO0X3AD': 'US8220',
 'CGXWUEF06V': 'US8221',
 'CF3C4RSOUY': 'US8222',
 'CO8O4SVZGO': 'US8223',
 'CXDHG14DBR': 'US8224',
 'C0PFBRITGM': 'US8225',
 'CKN7F02ZCB': 'US8226',
 'CE11FRWSD9': 'US8227',
 'C6X44JY3NR': 'US8228',
 'C722IB20ZE': 'US8229',
 'CQ8W877WO3': 'US8230',
 'CEVGABTAE5': 'US8231',
 'CT0IBPV84W': 'US8232',
 'CNQ2BUEWD7': 'US8233',
 'C98IHA5642': 'US8234',
 'C2P23LVP2T': 'US8235',
 'C5FRQTOB1L': 'US8236',
 'CJZ52VBI52': 'US8237',
 'CV4TU15PCF': 'US8238',
 'C1YRE47SN3': 'US8239',
 'CBN63SCI9D': 'US8240',
 'CPDFNUUHCX': 'US8241',
 'CSEASXPEU5': 'US8242',
 'CL1Y5MQFOO': 'US8243',
 'C4F5LZYD7M': 'US8244',
 'CU3XPPOB3K': 'US8245',
 'C34D104L71': 'US8246',
 'C25X0A4MR6': 'US8247',
 'CMAJ82GG3F': 'US8248',
 'CKCJ9F84NU': 'US8249',
 'CR8N2LGQLD': 'US8250',
 'C5HZ9EAZ5V': 'US8251',
 'CPIB38PMMB': 'US8252',
 'CYNIW17YO4': 'US8253',
 'CNZAJOS25Q': 'US8254'}

In [11]:
df_8["UserID"] = df_8["CUST_ID"].map(user_map)
df_8 = df_8.drop(columns=["CUST_ID"])

cols = ["UserID"] + [c for c in df_8.columns if c != "UserID"]
df_8 = df_8[cols]

df_8.head()

   UserID       DATE       EXP_TYPE  AMOUNT TransactionID
0  US8001  9/11/2015   Motor/Travel   20.27   TRX8_000001
1  US8001   2/8/2017   Motor/Travel   12.85   TRX8_000002
2  US8001   8/1/2015        Housing  383.80   TRX8_000003
3  US8001  3/16/2019  Entertainment    5.72   TRX8_000004
4  US8001  5/15/2015  Entertainment   11.06   TRX8_000005

In [12]:
# check all EXP_TYPE values
df_8["EXP_TYPE"].unique()

array(['Motor/Travel', 'Housing', 'Entertainment', 'Groceries', 'Savings',
       'Bills and Utilities', 'Clothing', 'Tax', 'Health', 'Fines',
       'Education', 'Gambling'], dtype=object)

In [13]:
# Rename EXP_TYPE to Category
df_8 = df_8.rename(columns={"EXP_TYPE": "Category"})
df_8.head()

   UserID       DATE       Category  AMOUNT TransactionID
0  US8001  9/11/2015   Motor/Travel   20.27   TRX8_000001
1  US8001   2/8/2017   Motor/Travel   12.85   TRX8_000002
2  US8001   8/1/2015        Housing  383.80   TRX8_000003
3  US8001  3/16/2019  Entertainment    5.72   TRX8_000004
4  US8001  5/15/2015  Entertainment   11.06   TRX8_000005

In [14]:
# Create Type column
expense_categories = [
    'Motor/Travel', 'Housing', 'Entertainment', 'Groceries', 'Savings',
    'Bills and Utilities', 'Clothing', 'Tax', 'Health', 'Fines',
    'Education', 'Gambling'
]

df_8["Type"] = df_8["Category"].apply(
    lambda x: "Expense" if x in expense_categories else "Income"
)

In [15]:
df_8[["Category", "Type"]].head(20)

         Category     Type
0    Motor/Travel  Expense
1    Motor/Travel  Expense
2         Housing  Expense
3   Entertainment  Expense
4   Entertainment  Expense
5    Motor/Travel  Expense
6   Entertainment  Expense
7   Entertainment  Expense
8       Groceries  Expense
9   Entertainment  Expense
10      Groceries  Expense
11      Groceries  Expense
12   Motor/Travel  Expense
13      Groceries  Expense
14  Entertainment  Expense
15      Groceries  Expense
16  Entertainment  Expense
17        Savings  Expense
18  Entertainment  Expense
19      Groceries  Expense

In [16]:
df_8.head()

   UserID       DATE       Category  AMOUNT TransactionID     Type
0  US8001  9/11/2015   Motor/Travel   20.27   TRX8_000001  Expense
1  US8001   2/8/2017   Motor/Travel   12.85   TRX8_000002  Expense
2  US8001   8/1/2015        Housing  383.80   TRX8_000003  Expense
3  US8001  3/16/2019  Entertainment    5.72   TRX8_000004  Expense
4  US8001  5/15/2015  Entertainment   11.06   TRX8_000005  Expense

In [17]:
# creating Merchant column 
df_8["Merchant"] = " "
df_8.head()

   UserID       DATE       Category  AMOUNT TransactionID     Type Merchant
0  US8001  9/11/2015   Motor/Travel   20.27   TRX8_000001  Expense
1  US8001   2/8/2017   Motor/Travel   12.85   TRX8_000002  Expense
2  US8001   8/1/2015        Housing  383.80   TRX8_000003  Expense
3  US8001  3/16/2019  Entertainment    5.72   TRX8_000004  Expense
4  US8001  5/15/2015  Entertainment   11.06   TRX8_000005  Expense

In [18]:
# creating Account Name column 
df_8["Account_Name"] = " "
df_8.head()

,UserID,DATE,Category,AMOUNT,TransactionID,Type,Merchant,Account_Name
0,US8001,9/11/2015,Motor/Travel,20.27,TRX8_000001,Expense,,
1,US8001,2/8/2017,Motor/Travel,12.85,TRX8_000002,Expense,,
2,US8001,8/1/2015,Housing,383.80,TRX8_000003,Expense,,
3,US8001,3/16/2019,Entertainment,5.72,TRX8_000004,Expense,,
4,US8001,5/15/2015,Entertainment,11.06,TRX8_000005,Expense,,

In [19]:
# Generate Descriptions Randomly

import numpy as np

description_map = {
    "Motor/Travel": [
        "Taxi fare to destination",
        "Fuel purchase at local station",
        "Bus fare payment",
        "Ride service payment",
        "Parking fee"
    ],
    "Housing": [
        "Monthly rent payment",
        "House maintenance charges",
        "Property service fee"
    ],
    "Entertainment": [
        "Movie ticket purchase",
        "Online streaming subscription",
        "Concert or event payment"
    ],
    "Groceries": [
        "Grocery shopping at supermarket",
        "Bought vegetables and fruits",
        "Household daily essentials"
    ],
    "Savings": [
        "Transfer to savings account",
        "Automatic savings deposit"
    ],
    "Bills and Utilities": [
        "Electricity bill payment",
        "Water bill settlement",
        "Internet bill payment",
        "Gas bill charges"
    ],
    "Clothing": [
        "Clothing purchase",
        "Bought new apparel",
        "Fashion store transaction"
    ],
    "Tax": [
        "Income tax payment",
        "Government tax deduction",
        "Local tax settlement"
    ],
    "Health": [
        "Pharmacy medical supplies",
        "Hospital consultation payment",
        "Lab test fees"
    ],
    "Fines": [
        "Traffic fine payment",
        "Late fee charge",
        "Government penalty fee"
    ],
    "Education": [
        "Course enrollment fee",
        "Online class subscription",
        "School-related payment"
    ],
    "Gambling": [
        "Casino game transaction",
        "Online betting payment",
        "Lottery ticket purchase"
    ]
}

def generate_description(category):
    if category in description_map:
        return np.random.choice(description_map[category])
    return "Miscellaneous transaction"
    

df_8["Transaction Description"] = df_8["Category"].apply(generate_description)

df_8[["Category", "Transaction Description"]].head(20)

         Category          Transaction Description
0    Motor/Travel         Taxi fare to destination
1    Motor/Travel             Ride service payment
2         Housing        House maintenance charges
3   Entertainment         Concert or event payment
4   Entertainment            Movie ticket purchase
5    Motor/Travel   Fuel purchase at local station
6   Entertainment    Online streaming subscription
7   Entertainment         Concert or event payment
8       Groceries     Bought vegetables and fruits
9   Entertainment         Concert or event payment
10      Groceries     Bought vegetables and fruits
11      Groceries  Grocery shopping at supermarket
12   Motor/Travel                 Bus fare payment
13      Groceries       Household daily essentials
14  Entertainment         Concert or event payment
15      Groceries  Grocery shopping at supermarket
16  Entertainment    Online streaming subscription
17        Savings        Automatic savings deposit
18  Entertainment    Online streaming subscription
19      Groceries       Household daily essentials

In [20]:
df_8.head()

,UserID,DATE,Category,AMOUNT,TransactionID,Type,Merchant,Account_Name,Transaction Description
0,US8001,9/11/2015,Motor/Travel,20.27,TRX8_000001,Expense,,,Taxi fare to destination
1,US8001,2/8/2017,Motor/Travel,12.85,TRX8_000002,Expense,,,Ride service payment
2,US8001,8/1/2015,Housing,383.80,TRX8_000003,Expense,,,House maintenance charges
3,US8001,3/16/2019,Entertainment,5.72,TRX8_000004,Expense,,,Concert or event payment
4,US8001,5/15/2015,Entertainment,11.06,TRX8_000005,Expense,,,Movie ticket purchase

In [21]:
# creating Currency  column 
df_8["Currency "] = " "
df_8.head()

,UserID,DATE,Category,AMOUNT,TransactionID,Type,Merchant,Account_Name,Transaction Description,Currency
0,US8001,9/11/2015,Motor/Travel,20.27,TRX8_000001,Expense,,,Taxi fare to destination,
1,US8001,2/8/2017,Motor/Travel,12.85,TRX8_000002,Expense,,,Ride service payment,
2,US8001,8/1/2015,Housing,383.80,TRX8_000003,Expense,,,House maintenance charges,
3,US8001,3/16/2019,Entertainment,5.72,TRX8_000004,Expense,,,Concert or event payment,
4,US8001,5/15/2015,Entertainment,11.06,TRX8_000005,Expense,,,Movie ticket purchase,

In [22]:
# Rename DATE and AMOUNT 
df_8 = df_8.rename(columns={"DATE": "Date"})
df_8 = df_8.rename(columns={"AMOUNT": "Amount"})
df_8 = df_8.rename(columns={"Account_Name": "Account Name"})
df_8.head()

,UserID,Date,Category,Amount,TransactionID,Type,Merchant,Account Name,Transaction Description,Currency
0,US8001,9/11/2015,Motor/Travel,20.27,TRX8_000001,Expense,,,Taxi fare to destination,
1,US8001,2/8/2017,Motor/Travel,12.85,TRX8_000002,Expense,,,Ride service payment,
2,US8001,8/1/2015,Housing,383.80,TRX8_000003,Expense,,,House maintenance charges,
3,US8001,3/16/2019,Entertainment,5.72,TRX8_000004,Expense,,,Concert or event payment,
4,US8001,5/15/2015,Entertainment,11.06,TRX8_000005,Expense,,,Movie ticket purchase,

In [23]:
# Check for NULL values in each required column
df_8[["Date", "Category", "Amount", "UserID", "TransactionID"]].isna().sum()

Date             0
Category         0
Amount           0
UserID           0
TransactionID    0
dtype: int64

In [24]:
# Check for EMPTY string values (“ ”) in those columns
(df_8[["Date", "Category", "Amount", "UserID", "TransactionID"]] == "").sum()

Date             0
Category         0
Amount           0
UserID           0
TransactionID    0
dtype: int64

In [25]:
# Check for rows where columns are BLANK or NULL

missing_rows = df_8[
    df_8["Date"].isna() |
    df_8["Category"].isna() |
    df_8["Amount"].isna() |
    df_8["UserID"].isna() |
    df_8["TransactionID"].isna() |
    (df_8["Category"].str.strip() == "") |
    (df_8["UserID"].str.strip() == "")
]

missing_rows.head()

Empty DataFrame
Columns: [UserID, Date, Category, Amount, TransactionID, Type, Merchant, Account Name, Transaction Description, Currency ]
Index: []

In [26]:
# Check if Amount has invalid values (0, negative, NaN

df_8["Amount"] = pd.to_numeric(df_8["Amount"], errors="coerce")

# Check invalid values
invalid_amounts = df_8[
    df_8["Amount"].isna() | (df_8["Amount"] <= 0)
]

print("Invalid Amount Rows:", len(invalid_amounts))
invalid_amounts.head()

Invalid Amount Rows: 0

Empty DataFrame
Columns: [UserID, Date, Category, Amount, TransactionID, Type, Merchant, Account Name, Transaction Description, Currency ]
Index: []

In [27]:
print("Null check:")
print(df_8.isna().sum())

print("\nEmpty string check:")
print((df_8 == "").sum())

print("\nTotal rows:", len(df_8))
print("Rows with ANY missing critical fields:", len(missing_rows))

Null check:
UserID                     0
Date                       0
Category                   0
Amount                     0
TransactionID              0
Type                       0
Merchant                   0
Account Name               0
Transaction Description    0
Currency                   0
dtype: int64

Empty string check:
UserID                     0
Date                       0
Category                   0
Amount                     0
TransactionID              0
Type                       0
Merchant                   0
Account Name               0
Transaction Description    0
Currency                   0
dtype: int64

Total rows: 1040203
Rows with ANY missing critical fields: 0

In [28]:
df_8["UserID"].nunique()

254

In [29]:
df_8["UserID"].unique()

array(['US8001', 'US8002', 'US8003', 'US8004', 'US8005', 'US8006',
       'US8007', 'US8008', 'US8009', 'US8010', 'US8011', 'US8012',
       'US8013', 'US8014', 'US8015', 'US8016', 'US8017', 'US8018',
       'US8019', 'US8020', 'US8021', 'US8022', 'US8023', 'US8024',
       'US8025', 'US8026', 'US8027', 'US8028', 'US8029', 'US8030',
       'US8031', 'US8032', 'US8033', 'US8034', 'US8035', 'US8036',
       'US8037', 'US8038', 'US8039', 'US8040', 'US8041', 'US8042',
       'US8043', 'US8044', 'US8045', 'US8046', 'US8047', 'US8048',
       'US8049', 'US8050', 'US8051', 'US8052', 'US8053', 'US8054',
       'US8055', 'US8056', 'US8057', 'US8058', 'US8059', 'US8060',
       'US8061', 'US8062', 'US8063', 'US8064', 'US8065', 'US8066',
       'US8067', 'US8068', 'US8069', 'US8070', 'US8071', 'US8072',
       'US8073', 'US8074', 'US8075', 'US8076', 'US8077', 'US8078',
       'US8079', 'US8080', 'US8081', 'US8082', 'US8083', 'US8084',
       'US8085', 'US8086', 'US8087', 'US8088', 'US8089', 'US8090',
       'US8091', 'US8092', 'US8093', 'US8094', 'US8095', 'US8096',
       'US8097', 'US8098', 'US8099', 'US8100', 'US8101', 'US8102',
       'US8103', 'US8104', 'US8105', 'US8106', 'US8107', 'US8108',
       'US8109', 'US8110', 'US8111', 'US8112', 'US8113', 'US8114',
       'US8115', 'US8116', 'US8117', 'US8118', 'US8119', 'US8120',
       'US8121', 'US8122', 'US8123', 'US8124', 'US8125', 'US8126',
       'US8127', 'US8128', 'US8129', 'US8130', 'US8131', 'US8132',
       'US8133', 'US8134', 'US8135', 'US8136', 'US8137', 'US8138',
       'US8139', 'US8140', 'US8141', 'US8142', 'US8143', 'US8144',
       'US8145', 'US8146', 'US8147', 'US8148', 'US8149', 'US8150',
       'US8151', 'US8152', 'US8153', 'US8154', 'US8155', 'US8156',
       'US8157', 'US8158', 'US8159', 'US8160', 'US8161', 'US8162',
       'US8163', 'US8164', 'US8165', 'US8166', 'US8167', 'US8168',
       'US8169', 'US8170', 'US8171', 'US8172', 'US8173', 'US8174',
       'US8175', 'US8176', 'US8177', 'US8178', 'US8179', 'US8180',
       'US8181', 'US8182', 'US8183', 'US8184', 'US8185', 'US8186',
       'US8187', 'US8188', 'US8189', 'US8190', 'US8191', 'US8192',
       'US8193', 'US8194', 'US8195', 'US8196', 'US8197', 'US8198',
       'US8199', 'US8200', 'US8201', 'US8202', 'US8203', 'US8204',
       'US8205', 'US8206', 'US8207', 'US8208', 'US8209', 'US8210',
       'US8211', 'US8212', 'US8213', 'US8214', 'US8215', 'US8216',
       'US8217', 'US8218', 'US8219', 'US8220', 'US8221', 'US8222',
       'US8223', 'US8224', 'US8225', 'US8226', 'US8227', 'US8228',
       'US8229', 'US8230', 'US8231', 'US8232', 'US8233', 'US8234',
       'US8235', 'US8236', 'US8237', 'US8238', 'US8239', 'US8240',
       'US8241', 'US8242', 'US8243', 'US8244', 'US8245', 'US8246',
       'US8247', 'US8248', 'US8249', 'US8250', 'US8251', 'US8252',
       'US8253', 'US8254'], dtype=object)

In [30]:
df_8["UserID"].value_counts()

UserID
US8107    9885
US8223    9023
US8247    8919
US8088    8827
US8039    8711
          ...
US8251    1102
US8100    1066
US8149    1049
US8135    1041
US8096    1005
Name: count, Length: 254, dtype: int64

In [31]:
print("Total transactions:", len(df_8))

Total transactions: 1040203

In [32]:
import os

# Make sure folder exists
os.makedirs("Tofinal", exist_ok=True)

# Save file into that folder
df_8.to_csv("Tofinal/transaction.csv", index=False)
print("File saved successfully: Tofinal/transaction.csv")

File saved successfully: Tofinal/transaction.csv